### ISSUE TITLE
Writing good commit messages

### ISSUE THREAD

**Issue by apisarek** [osdnk/sysopy#1]
I know that "kurwa" is a really versatile word, but I don't think that it can be considered a verb.

One of your commit messages - "kurwa no chyba mnie popierdolilo aby dawac size 10000" 

https://juffalow.com/other/write-good-git-commit-message

**Comment by osdnk** [comment]
Thank you for your message. I took deep look on your issue.
You're absolutely right that this messages should be provided in a one way. Maybe naming every of them "kurwa" is a nice idea?

**Comment by osdnk** [comment]
Thank you for your issus. However, it seems to be inactive thus I decided to close it
